"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

export default function TaxPage() {
  const router = useRouter();
  const [tax, setTax] = useState<any>(null);

  useEffect(() => {
    const stored = localStorage.getItem("analysisResult");
    if (!stored) {
      router.push("/");
      return;
    }
    const parsed = JSON.parse(stored);
    setTax(parsed.tax_snapshot);
  }, []);

  if (!tax) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-black via-slate-900 to-black text-white flex items-center justify-center">
        Loading tax snapshot…
      </div>
    );
  }

  const taxEstimate = tax.tax_estimate;
  const oldRegime = taxEstimate?.old_regime;
  const newRegime = taxEstimate?.new_regime_2025_26;

  return (
    <main className="min-h-screen bg-gradient-to-br from-black via-slate-900 to-black text-white px-6 py-20">
      <div className="max-w-7xl mx-auto space-y-20">

        {/* HEADER */}
        <section className="space-y-4">
          <h1 className="text-5xl font-bold">
            🧾 <span className="text-emerald-400">Tax Snapshot</span>
          </h1>
          <p className="text-slate-400 max-w-3xl">
            A structured, explainable view of your tax-relevant income, deductions,
            and estimated liabilities — derived strictly from your bank statement.
          </p>
        </section>

        {/* HOW IT WORKS */}
        <section className="rounded-xl border border-white/10 bg-white/5 p-5 text-sm text-slate-400">
          <p className="font-semibold text-white mb-2">
            How this Tax Snapshot works
          </p>
          <ul className="space-y-1 list-disc pl-5">
            <li>All figures are derived from your bank statement</li>
            <li>No tax numbers are guessed or generated by AI</li>
            <li>AI is used only to explain patterns and gaps</li>
            <li>This is an estimate, not an ITR filing</li>
          </ul>
        </section>

        {/* METRICS */}
        <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Metric title="Gross Income" value={tax.tax_base?.gross_income} color="emerald" />
          <Metric
            title="80C + 80D + Home Loan"
            value={
              (tax.tax_base?.deductions_claimed?.["80C"] || 0) +
              (tax.tax_base?.deductions_claimed?.["80D"] || 0) +
              (tax.tax_base?.deductions_claimed?.home_loan_interest || 0)
            }
            color="cyan"
          />
          <Metric
            title="Optimization Gap"
            value={tax.tax_gaps?.potential_80C_remaining}
            color="rose"
          />
        </section>

        {/* TAX COMPARISON */}
        <Section title="Tax Comparison (Old vs New Regime)">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-fade-up">

            {/* OLD REGIME */}
            <div className="rounded-xl border border-white/10 bg-white/5 p-6">
              <p className="text-sm text-slate-400">Old Regime</p>
              <p className="mt-2">
                Taxable Income: <b>₹{oldRegime?.taxable_income}</b>
              </p>
              <p className="mt-1 text-lg font-semibold text-rose-400">
                Estimated Tax: ₹{oldRegime?.estimated_tax}
              </p>
              <p className="text-xs text-slate-400 mt-2">
                Includes 80C / 80D deductions
              </p>
            </div>

            {/* NEW REGIME */}
            <div className="rounded-xl border border-emerald-400/30 bg-emerald-400/10 p-6">
              <p className="text-sm text-slate-400">New Regime (2025–26)</p>
              <p className="mt-2">
                Taxable Income: <b>₹{newRegime?.taxable_income}</b>
              </p>
              <p className="mt-1 text-lg font-semibold text-emerald-400">
                Estimated Tax: ₹{newRegime?.estimated_tax}
              </p>
              <p className="text-xs text-slate-400 mt-2">
                Standard deduction applied:{" "}
                {newRegime?.standard_deduction_applied ? "Yes" : "No"}
              </p>
            </div>

          </div>

          {/* RECOMMENDED */}
          <div className="mt-6 rounded-lg bg-white/5 border border-white/10 p-4">
            <p className="text-sm text-slate-400">Recommended Regime</p>
            <p className="text-xl font-semibold text-emerald-400">
              {taxEstimate?.recommended_regime?.toUpperCase()}
            </p>
          </div>
        </Section>

        {/* DEDUCTIONS */}
        <Section title="Deductions & Utilization">
          <Table
            headers={["Section", "Claimed", "Maximum Allowed", "Status"]}
            rows={[
              [
                "80C",
                `₹${tax.tax_base?.deductions_claimed?.["80C"] || 0}`,
                "₹150,000",
                tax.tax_gaps?.sections_not_utilized?.includes("80C")
                  ? "Not Utilized"
                  : "Used / Partially Used",
              ],
              [
                "80D",
                `₹${tax.tax_base?.deductions_claimed?.["80D"] || 0}`,
                "₹25,000",
                tax.tax_gaps?.sections_not_utilized?.includes("80D")
                  ? "Not Utilized"
                  : "Used",
              ],
            ]}
          />
        </Section>

        {/* SIGNALS */}
        <Section title="Detected Signals">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Insight good={tax.tax_signals?.salary_detected} text="Salary income detected" />
            <Insight good={tax.tax_signals?.tds_detected} text="TDS detected" />
            <Insight good={tax.tax_signals?.investment_activity_detected} text="Investment activity detected" />
            <Insight
              good={!tax.tax_signals?.medical_spend_without_insurance}
              text="Medical spend without insurance"
            />
          </div>
        </Section>

        {/* DISCLAIMER */}
        <section className="rounded-2xl border border-yellow-400/30 bg-yellow-400/10 p-6 text-sm text-yellow-300">
          <p className="font-semibold mb-2">Important Disclaimer</p>
          <p>
            This Tax Snapshot is an informational analysis generated from transaction data.
            It is NOT a tax filing, ITR preparation, or legal advisory service.
          </p>
        </section>

        <button
          onClick={() => router.push("/dashboard")}
          className="text-emerald-400 hover:underline"
        >
          ← Back to Dashboard
        </button>

      </div>
    </main>
  );
}

/* ================= HELPERS ================= */

const colorMap: any = {
  emerald: "text-emerald-400",
  cyan: "text-cyan-400",
  rose: "text-rose-400",
};

function Metric({ title, value, color }: any) {
  return (
    <div className="rounded-2xl bg-white/5 border border-white/10 p-6">
      <p className="text-sm text-slate-400">{title}</p>
      <p className={`text-3xl font-bold mt-2 ${colorMap[color]}`}>
        ₹{value}
      </p>
    </div>
  );
}

function Section({ title, children }: any) {
  return (
    <section className="space-y-4">
      <h2 className="text-2xl font-semibold">{title}</h2>
      {children}
    </section>
  );
}

function Table({ headers, rows }: any) {
  return (
    <div className="overflow-hidden rounded-xl border border-white/10">
      <table className="w-full text-sm">
        <thead className="bg-white/5 text-slate-400">
          <tr>
            {headers.map((h: string) => (
              <th key={h} className="px-4 py-3 text-left">{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row: string[], i: number) => (
            <tr key={i} className="border-t border-white/10">
              {row.map((cell, j) => (
                <td key={j} className="px-4 py-3">{cell}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function Insight({ good, text }: any) {
  return (
    <div className={`rounded-xl p-4 border ${
      good ? "border-green-400/30 bg-green-400/10" : "border-red-400/30 bg-red-400/10"
    }`}>
      <p className="text-sm">{good ? "✅" : "⚠️"} {text}</p>
    </div>
  );
}